spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: yang-gateway
          uri: http://127.0.0.1:8070
          predicates:
            - Path=/gateway/**
            - Custom=yang,\d+