spring:
  application:
    name: seata-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.52.129:8848
        username: nacos
        password: nacos
        namespace: f4677f31-643c-492b-861f-9084f6db25bb
        group: SEATA_GROUP
server:
  port: 8050
ribbon:
  eager-load:
    enabled: true
    clients: seata-stock
seata:
  registry:
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: 192.168.52.129:8848
      username: nacos
      password: nacos
      namespace: f4677f31-643c-492b-861f-9084f6db25bb
    type: nacos
  config:
    nacos:
      server-addr: 192.168.52.129:8848
      group: SEATA_GROUP
      namespace: f4677f31-643c-492b-861f-9084f6db25bb
      password: nacos
      username: nacos
    type: nacos
  enable-auto-data-source-proxy: true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default