spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        namespace: 20fbb1f6-fb66-4a15-ba29-aa19a1a48dbb
        username: nacos
        password: nacos
        server-addr: 192.168.52.129:8848
server:
  port: 8070